In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/dhs_children_combined.csv")

df.head()

,country,age_months,sex,weight_kg,height_cm,haz,waz,whz,stunting_status,underweight_status,...,iycf_applicable,grains_roots_tubers,legumes_nuts,dairy,flesh_foods,eggs,vitamin_a_fruits_veg,other_fruits_veg,dietary_diversity_score,min_dietary_diversity_met
0,India,12.0,F,11.1,90.0,5.65,1.50,-1.39,normal,normal,...,True,1.0,0.0,1.0,0.0,1.0,0.0,1.0,4.0,True
1,India,25.0,F,14.5,102.7,4.61,1.53,-1.16,normal,normal,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,India,39.0,M,12.7,109.7,2.98,-1.31,-4.32,normal,normal,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,India,57.0,M,26.2,109.4,0.13,2.72,3.93,normal,normal,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,India,11.0,M,13.3,76.6,0.51,3.04,3.50,normal,normal,...,True,1.0,1.0,1.0,1.0,1.0,0.0,1.0,6.0,True

In [3]:
df.shape

(213328, 24)

In [4]:
df.columns.tolist()

['country',
 'age_months',
 'sex',
 'weight_kg',
 'height_cm',
 'haz',
 'waz',
 'whz',
 'stunting_status',
 'underweight_status',
 'wasting_status',
 'wealth_index',
 'mother_education',
 'currently_breastfeeding',
 'iycf_applicable',
 'grains_roots_tubers',
 'legumes_nuts',
 'dairy',
 'flesh_foods',
 'eggs',
 'vitamin_a_fruits_veg',
 'other_fruits_veg',
 'dietary_diversity_score',
 'min_dietary_diversity_met']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 213328 entries, 0 to 213327
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   country                    213328 non-null  str
 1   age_months                 213328 non-null  float64
 2   sex                        213328 non-null  str
 3   weight_kg                  213328 non-null  float64
 4   height_cm                  213328 non-null  float64
 5   haz                        213328 non-null  float64
 6   waz                        213328 non-null  float64
 7   whz                        213328 non-null  float64
 8   stunting_status            213328 non-null  str
 9   underweight_status         213328 non-null  str
 10  wasting_status             213328 non-null  str
 11  wealth_index               213328 non-null  int64
 12  mother_education           213328 non-null  int64
 13  currently_breastfeeding    213328 non-null  bool
 14  iycf_applicable            213328 non-null  bool
 15  grains_roots_tubers        116471 non-null  float64
 16  legumes_nuts               116471 non-null  float64
 17  dairy                      116471 non-null  float64
 18  flesh_foods                116471 non-null  float64
 19  eggs                       116471 non-null  float64
 20  vitamin_a_fruits_veg       116471 non-null  float64
 21  other_fruits_veg           116471 non-null  float64
 22  dietary_diversity_score    116471 non-null  float64
 23  min_dietary_diversity_met  116471 non-null  object
dtypes: bool(2), float64(14), int64(2), object(1), str(5)
memory usage: 36.2+ MB

In [6]:
df.describe()

,age_months,weight_kg,height_cm,haz,waz,whz,wealth_index,mother_education,grains_roots_tubers,legumes_nuts,dairy,flesh_foods,eggs,vitamin_a_fruits_veg,other_fruits_veg,dietary_diversity_score
count,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,213328.000000,116471.000000,116471.000000,116471.000000,116471.000000,116471.000000,116471.000000,116471.000000,116471.000000
mean,30.095393,10.921011,84.437356,-1.367992,-1.334716,-0.778739,2.665970,1.563597,0.508942,0.148260,0.420980,0.097578,0.148277,0.226125,0.343905,1.894068
std,17.209823,3.316099,13.866700,1.719720,1.233409,1.492363,1.379011,0.974277,0.499922,0.355359,0.493719,0.296744,0.355376,0.418323,0.475012,1.934896
min,0.000000,1.700000,45.000000,-6.000000,-5.970000,-5.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15.000000,8.600000,74.500000,-2.440000,-2.130000,-1.640000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,30.000000,11.000000,86.000000,-1.470000,-1.360000,-0.770000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,45.000000,13.200000,95.100000,-0.430000,-0.560000,0.100000,4.000000,2.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,3.000000
max,59.000000,29.800000,120.000000,6.000000,4.970000,5.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000